#!/bin/zsh

export EDITOR="nvim"
export TERMINAL="alacritty"
# export BROWSER="firefox -private-window"
export BROWSER="firefox"

# Folders
export XDG_CONFIG_HOME="$HOME/.config"
export PICS="$HOME/pics"
export DOCS="$HOME/docs"
export MOOSIC="$HOME/moosic"
export VIDS="$HOME/videos"

# Scripts
export PATH="$PATH:/home/abhinand/scripts/all"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# export HISTCONTROL=ignoredups
# export PAGER="/usr/bin/less"

# MariaDB
export MARIADB_HOME="$XDG_CONFIG_HOME/mariadb"

# Latex
export PATH="$PATH:/usr/local/texlive/2023/bin/x86_64-linux"
export MANPATH="$MANPATH:/usr/local/texlive/2023/texmf-dist/man"
export INFOPATH="$INFOPATH:/usr/local/texlive/2023/texmf-dist/doc/info"

# Prompt
# export PS1=

# Auto-login
case "$(tty)" in
*"/tty1") startx ;;
esac
