# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# Inserts a blank line between shell prompts
# add_newline = true

format = """
$username\
$hostname\
$directory\
$time\
$shell\
$line_break"""

# Replace the '❯' symbol in the prompt with '➜'
[character]
disabled=true
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold red)' # The 'error_symbol' segment is being set to '➜' with the color 'bold red'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
always_show_remote = true

[directory]
format = '\[[CrinklyNinja | $path]($style)\] ' # Must replace CrinklyNinja with $user
truncation_length = 1


